---
#server reachability
- hosts: localhost
  gather_facts: false
  ignore_errors: yes
  vars: 
    output_var: ""
    res_var: "success"
    inv_var: "fail"
  tasks:
  
    - block:   
      - name: Check if Host is present in Inventory
        set_fact:
          output_var: "{{output_var}} \n {{host}} server is present in inventory."
          inv_var: "success"
        when: (host in hostvars)

      - set_fact:
          output_var: "{{output_var}}\n \n  [******ERROR OCCURED*******]  \n \n {{host}} server is absent in inventory."
          res_var: "failed"
        when: (host not in hostvars)
      
      - name: Server Reachability Check
        ping: 
        when: (inv_var == "success")
        delegate_to: "{{host}}"
        ignore_unreachable: true
        register: ping_var

      - debug:
           msg: "{{ping_var}}"
           
      - set_fact:
          output_var: "{{output_var}}\n \n  [******ERROR OCCURED*******]  \n \n {{host}} is Unreachable. \n {{ping_var.msg}}."
          res_var: "failed"
        when: ((ping_var.unreachable is defined) or (ping_var.ping is not defined)) and (inv_var == "success")
        ignore_errors: yes

      - set_fact:
          output_var: "{{output_var}} \n {{host}} Server is Reachable from Ansible. \n"
        when: ((ping_var.unreachable is not defined) or (ping_var.ping is defined)) and (inv_var == "success")
        ignore_errors: yes


      rescue:
      - name: "Error occurred while pinging the server \n"
        set_fact:
          output_var: "{{output_var}} \n \n  [******ERROR OCCURED*******]  \n \n Unable to reach the server."
          res_var: "failed"

    - block:
        - set_stats:
              data:
                TASK_WorkNotes: " {{output_var}} \n"
      when: res_var == "success"

    - block:
        - set_stats:
              data:
                TASK_SYSID: "{{sys_id}}"
                TASK_STATE: 1
                TASK_WorkNotes: "{{output_var}} \n \n 
                EXECUTION FAILED, Escalating Task for Manual Intervention"

        - name: Job Validation
          debug:
             msg: "Job Failed"
          failed_when: 
            - res_var == "failed"
          ignore_errors: no

      when: res_var == "failed"
